<a href="https://colab.research.google.com/github/pramodsingh0507/Assignment_Datastrucures/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Theory Question Example Ques:2) Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# np.mean()
import numpy as np

a = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(a)
mean_value


3.0

In [ ]:
# np.average()
import numpy as np

a = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 1])  # Equal weights, same as np.mean
average_value = np.average(a, weights=weights)  # Output: 3.0

# With different weights
weights = np.array([1, 2, 3, 4, 5])
weighted_average_value = np.average(a, weights=weights)  # Output: 4.0

print(average_value)
print(weighted_average_value)



3.0
3.6666666666666665


In [ ]:
# Ques-3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [ ]:
# Reversing a 1D Array
# Using Slicing
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 3 2 1]


In [ ]:
# Reversing a 2D Array
#Reversing Along Axis 0 (Rows)

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reverse along axis 0 (rows)
reversed_axis0 = arr[::-1, :]

print(reversed_axis0)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Reversing Along Axis 1 (Columns)
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reverse along axis 1 (columns)
reversed_axis1 = arr[:, ::-1]

print(reversed_axis1)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# Reversing Along Both Axes
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reverse along both axes
reversed_both = arr[::-1, ::-1]

print(reversed_both)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# Ques-4 How can you determine the data type of elements in a NumPy array?
# Discuss the importance of data types in memory management and performance.
# Create arrays with different data types
int_array = np.array([1, 2, 3, 4], dtype=np.int32)
float_array = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float64)
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)

# Determine data types
print(int_array.dtype)
print(float_array.dtype)
print(complex_array.dtype)

int32
float64
complex128


In [ ]:
# Ques 5 Define 'ndarray' in NumPy and explain their key features. How do they differ from the standard Python list?.

# ndarray
# Create a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Perform element-wise addition
result = arr + 10
print(result)

[[11 12 13]
 [14 15 16]]


In [ ]:
# Python List
# Create a 2D list
lst = [[1, 2, 3], [4, 5, 6]]

# Perform element-wise addition (requires nested loops)
result = [[x + 10 for x in row] for row in lst]
print(result)

[[11, 12, 13], [14, 15, 16]]


In [1]:
# Ques 7 . Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# vstack()
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)


Result of vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
# hstack()

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

# Stack horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[1 2 5]
 [3 4 6]]


In [ ]:
#  Ques:8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

In [4]:
# fliplr()

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip left to right
result_fliplr = np.fliplr(array_2d)

print("Original 2D array:")
print(array_2d)
print("\nFlipped left to right:")
print(result_fliplr)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Flipped left to right:
[[3 2 1]
 [6 5 4]]


In [5]:
# flipud()

# Flip up to down
result_flipud = np.flipud(array_2d)

print("\nFlipped up to down:")
print(result_flipud)




Flipped up to down:
[[4 5 6]
 [1 2 3]]


In [7]:
## Practical Questions
## Practical Questions

# Ques 1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 97  57  94]
 [ 46  14  49]
 [ 72 100  60]]

Transposed array:
[[ 97  46  72]
 [ 57  14 100]
 [ 94  49  60]]


In [8]:
## Ques-2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This creates an array with values from 0 to 9

# Print the original 1D array
print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Ques 3  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [9]:
# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Print the original 4x4 array
print("Original 4x4 array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 array with a border of zeros:")
print(array_with_border)

Original 4x4 array:
[[0.61969856 0.72751133 0.16709291 0.91488381]
 [0.97812944 0.42511945 0.01712644 0.71840874]
 [0.86453105 0.92448055 0.68073246 0.17802352]
 [0.44969453 0.63526445 0.26857994 0.54011849]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.61969856 0.72751133 0.16709291 0.91488381 0.        ]
 [0.         0.97812944 0.42511945 0.01712644 0.71840874 0.        ]
 [0.         0.86453105 0.92448055 0.68073246 0.17802352 0.        ]
 [0.         0.44969453 0.63526445 0.26857994 0.54011849 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [12]:
# Ques 4 Using NumPy, create an array of integers from 10 to 60 with a step of 5

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [13]:
# Ques 5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

# Print the results
print("Original array:")
print(string_array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalized:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [14]:
# Ques 6  Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Print the original and transformed arrays
print("Original array:")
print(words_array)

print("\nArray with spaces between characters:")
print(spaced_words_array)



Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [15]:
# Ques 7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Element-wise addition
addition = array1 + array2
print("Addition:\n", addition)

# Element-wise subtraction
subtraction = array1 - array2
print("\nSubtraction:\n", subtraction)

# Element-wise multiplication
multiplication = array1 * array2
print("\nMultiplication:\n", multiplication)

# Element-wise division
division = array1 / array2
print("\nDivision:\n", division)





Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [16]:
# Ques 8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Display the results
print("Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [18]:
# Ques 9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:", prime_numbers)


Random Integers:
 [215 731 104 939 352 259 443 844 827 893 626 201 574 394 995 419 104 400
 269 372 197 957 448 665 473 293 348 715 419  58 123 193 446 220 554 917
 813 675  20  24 587 487 279 371  92 146 580 464 157 137 586 976 100 584
 260 647 202 289 514 107 547  58 408 919 597 985 879 697 757 526 539 224
 330 999 193 772 649 433  15 777 311 276 766  96 187 311 163 397 624 229
 940  42 823 395 956 466 345 788 929 853]

Prime Numbers: [443, 827, 419, 269, 197, 293, 419, 193, 587, 487, 157, 137, 647, 107, 547, 919, 757, 193, 433, 311, 311, 163, 397, 229, 823, 929, 853]


In [22]:
# Ques 10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

import numpy as np

# Create a NumPy array representing daily temperatures for a month
# Here we are using random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=28)

# Reshape the array to represent weeks (4 weeks)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Averages:", weekly_averages)




Daily Temperatures:
 [33 17 25 18 16 34 32 30 34 17 35 34 35 25 26 26 26 30 32 35 29 33 34 32
 30 20 16 34]

Weekly Averages: [25.         30.         29.14285714 28.42857143]
